#AI 기초 연수 과정 Python With Google Colab

##Introduction


파이썬은 그 자체만으로도 훌륭한 다목적 프로그래밍 언어이지만, NumPy, SciPy, Matplotlib과 같은 몇 가지 인기 라이브러리를 사용하면 과학 계산을 위한 강력한 환경이 됩니다.

AI 기초 연수 과정의 수강생들은 대부분 프로그램이 경험이 없습니다. 따라서 초보자 수준에 맞춰진 튜토리얼로 이 수업을 통해 파이썬이 동작하는 메커니즘과 기억해야하는 주된 내용들만 숙지하셔도 학업 성취도가 아주 높다고 생각합니다.

In [ ]:
## Python 버전확인
!python --version

##Basics of Python

###Basic data types

####Numbers

숫자형이란 숫자 형태로 이루어진 자료형으로 우리가 흔히 잘 알고있는 정수(integer), 실수(float)등이 있다

In [ ]:
x = 3
print(x, type(x))

In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

Code 실습!

*   a = 3 / b = 5 일때 아래 연산을 코드로 구현하시오
  1. a + b
  2. a - b
  3. a * b
  



In [ ]:
## 아래에 코드 작성

In [ ]:
## augmented assigment(확장치환)
## x = x + 1
x += 1
print(x)

## x = x * 2
x *= 2
print(x)

In [ ]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

####Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print(type(t))

Now we let's look at the operations:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

####Strings

In [ ]:
hello = 'hello'   # String literals can use single quotes 작은따옴표
world = "world"   # or double quotes; it does not matter  큰따옴표

print(hello, world)
print(hello, len(hello)) ## len()함수는 길이를 출력한다

In [ ]:
hw = hello + ' ' + world  # String concatenation
print(hw)

Q. hw의 type은 무엇인가?

In [ ]:
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
hw13 = print(f'{hello} {world} {12}')       # f-string formatting
print(hw12)

String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

Q. 왼쪽 정렬은?

Q. 왼쪽 공백 제거하는 method?

Q. 오른쪽 공백 베거하는 method?

###Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

####Lists

리스트는 다른 프로그래밍 언어의 array, 특징은 다른 모든 자료형 저장 가능하다.

In [ ]:
xs = [3, 1, 2]    ## 리스트 생성하기
print(xs, xs[2])
print(xs[-1])     ## -1 index는 리스트 마지막 index를 의미한다

In [ ]:
xs[2] = 'foo'    # 리스트는 다른 자료형을 하나의 리스트에 저장할 수 있다
print(xs)

In [ ]:
xs.append('bar') # 새로운 element를 리스트 마지막에 추가
print(xs)

In [ ]:
x = xs.pop()     # 리스트의 마지막 element를 제거하고 할당
print(x, xs)

####Slicing

리스트 요소에 접근하는 방법 중 하나는 list Slicing이다.

In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)              # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])         # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])          # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])          # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])           # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])         # Slice indices can be negative; prints ["0, 1, 2, 3]"
print(nums[1:4:2])
print(nums[-1:-5:-1])

Q. a = [1, 2, 3, 4, 5, 6, 7]

   print(a[3:6])은 무엇인가?

####Dictionaries

딕셔너리는 key, value 쌍(pairs)을 저장하는 자료형

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # 딕셔너리 자료형 생성하기 / 딕셔너리 자료형은 {} 중괄호를 이용하여 생성한다
print(d)

In [ ]:
print(d['cat'])       # 딕셔너리 자료형 접근하기 위해서는 key값을 통해 value값에 접근한다

In [ ]:
print(d['cute'])      # value값에 접근하게 되면 어떻게 될까?

In [ ]:
d['fish'] = 'wet'     # 딕셔너리에 새로운 데이터(element) 추가하기
print(d)
print(d['fish'])

In [ ]:
print(d['monkey'])  # KeyError: 'monkey'라는 key값은 없기때문에 KeyError 발생

In [ ]:
del d['fish']        # 딕셔너리 데이터(element) 삭제하기
print(d)

####Sets

집합은 서로 다른 element들로 이루어진, 순서가 없는 모음

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # animals에 'cat'이 존재하는지 확인
print('fish' in animals)  # animals에 'fish'가 존재하는지 확인
print(type(animals))
print(animals)

In [ ]:
animals.add('fish')       # 집합에 'fish'라는 element 추가하기
print('fish' in animals)
print(len(animals))       # 집합에 저장된 element 갯수 출력하기

Code 실습!!
- animals 집합에 'tiger' elemnet 추가하기

In [ ]:
## 아래에 코드를 작성하시오

In [ ]:
animals.add('cat')       # 이미 집합에 있는 element를 추가하면 어떻게 될까?
print(len(animals))
animals.remove('cat')    # 집합에 있는 element 제거하기
print(len(animals))

Code 실습!!
- animals 집합에 'tiger' elemnet 제거하기

In [ ]:
## 아래에 코드를 작성하시오

####Tuples

튜플은 (변경 불가능한) 순서가 있는 값들의 리스트입니다. 튜플은 리스트와 여러 면에서 유사하지만, 가장 중요한 차이점은 딕셔너리의 key, value와 세트의 element로 사용될 수 있다는 점입니다. 반면 리스트는 사용할 수 없습니다.

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # tuple을 key로 사용하는 딕셔너리 생성
t = (5, 6)       # tuple 생성
print(d)
print(t)
print(type(t))
print(d[t])
print(d[(1, 2)])

###Functions

Python function은 `def` keyword를 이용해서 만들 수 있다.

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

##Numpy

파이썬에서 과학 계산을 위한 핵심 라이브러리는 Numpy입니다. Numpy는 고성능 다차원 배열 객체와 이 배열들을 다루는 도구를 제공합니다.

Numpy를 사용하기 위해서는, 먼저 `numpy`를 import 해야한다.

import한다는 의미는 다양한 다른 `library` 내 저장된 package, module, function, class 등을 불러오는 것이다.

In [ ]:
import numpy as np ## numpy를 줄여서 np로 사용하겠다

###Arrays

NumPy 배열은 다음과 같은 특징을 가진 데이터 구조입니다.

- 다차원 값의 격자: NumPy 배열은 여러 개의 차원으로 구성된 값들의 격자입니다. 즉, 1차원 배열(리스트와 유사), 2차원 배열(행렬), 3차원 이상의 배열 등 다양한 형태로 존재할 수 있습니다.
- 동일한 데이터 타입: NumPy 배열은 모든 요소가 동일한 데이터 타입으로 구성됩니다. 예를 들어, 모든 요소가 정수, 실수, 문자열 등으로만 이루어질 수 있습니다.
- 정수 인덱싱: NumPy 배열은 0 이상의 정수로 구성된 튜플을 사용하여 인덱싱됩니다. 이 튜플의 길이는 배열의 차원 수와 동일하며, 각 정수는 해당 차원에서의 요소 위치를 나타냅니다.
차원 수 & 배열 크기:
- 차원 수(rank): 배열의 차원 개수를 의미합니다. 예를 들어, 1차원 배열은 1, 2차원 배열은 2, 3차원 배열은 3의 차원 수를 가지고 있습니다.
- 배열 크기(shape): 배열의 각 차원에서 요소 개수를 나타내는 정수 튜플입니다. 예를 들어, 2차원 배열의 크기는 (행 개수, 열 개수) 형태로 표현됩니다.

파이썬 리스트를 사용해서 numpy array를 생성할 수 있으며 []대괄호를 이용해서 array 요소에 접근할 수 있다.

In [ ]:
a = np.array([1, 2, 3])  # rank 1, 1차원 array 생성하기
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # array의 element값 변경하기
print(a)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # rank 2, 2차원 array 생성하기
print(b)

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

numpy는 array를 생성하는 많은 function들을 제공한다.

In [ ]:
a = np.zeros((2,2))  # array의 모든 element가 0(zero)인 array 생성하기
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

Q. np.zeros, np.ones 사용 시 int(정수형)로 생성하기 위한 방법은 무엇일까?

In [ ]:
## 아래에 코드 작성
a = np.zeros((2,2), dtype=np.int64)
print(a)

b =

In [ ]:
c = np.full((2,2), 7) # constatn element로 이루어진 array 생성하기
print(c)

In [ ]:
d = np.eye(2)        # identity matrix(단위행렬) 생성하기
print(d)

In [ ]:
e = np.random.random((2,2)) # 0 ~ 1 사이의 무작위 실수 array 생성하기
print(e)

###Datatypes

Numpy array는 모든 element가 같은 data type으로 구성되어 있습니다.

Numpy는 다양한 숫자 데이터 타입을 지원하여 이를 이용해서 array를 생성할 수 있습니다.

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

###Array math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

In [ ]:
# Elementwise sum; both produce the array
print(x + y)         ## operater(연산자) 사용
print(np.add(x, y))  ## function 사용

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219 // 내적 연산
print(v.dot(w))
print(np.dot(v, w))

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))          # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
print(x)
print("transpose\n", x.T)  ## 전치행렬 생성하기

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

###Broadcasting

Broadcasting은 서로 다른 shape의 array 간에 연산을 수행할 때 사용되는 강력한 메커니즘입니다.

array의 shape을 변경하지 않고도 효율적으로 연산을 수행할 수 있다.

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

##Matplotlib

Matplotlib는 그래프를 그리는 라이브러리입니다.

간단하게 `matplotlib.pyplot` module에 대해서 학습

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
%matplotlib inline

###Plotting

The most important function in `matplotlib` is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1) ## np.pi는 파이 값을 반환
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine']) ## 범례

###Subplots

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)  ## 행, 렬, 위치
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()